---
#name: Md. Jubayer
surname: Md. Jubayer Hossain
#position: "Founder, Management Lead, Data Analyst"
#aboutme: Health Data Science, GIS and Remote Sesning, and Bioinformatics 
#address: "Center for Health Innovation, Research, Action, and Learning-Bangladesh(CHIRAL Bangladesh)"
#address: "Dhaka, Bangladesh"
#phone: +1 617 432 7004
#phone: +1 617 945 4383
email: "contact.jubayerhossain@gmail.com"
www: www.jhossain.com
github: hossainlab
linkedin: hossainmj
headcolor: 414141
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyr)
library(dplyr)
library(readr)
library(glue)
library(tibble)
library(lubridate)
library(here)
library(scales)
```


# Research Experiences
**<span style="font-size:1em;">Center for Health Innovation, Research, Action, and Learning - Bangladesh</span>** \hfill _Dhaka, Bangladesh_  
Founder, Management Lead & Data Analyst \hfill _June 2020 - Present_  

**<span style="font-size:1em;">International Centre for Diarrhoeal Disease Research, Bangladesh</span>** \hfill _Dhaka, Bangladesh_  
Research Intern, Health Systems and Population Studies Division \hfill _February 2022 - June 2022_ 
 
**<span style="font-size:1em;">Bio-Bio-1:: Bioinformatics Research Discussion Group</span>** \hfill _Dhaka, Bangladesh_  
Team Member, Bioinformatics Group \hfill _February 2016 - June 2019_ 

# Research Interests 
Applied Machine Learning in Public Health, GIS & Remote Sensing in Public Health, Quantitative Methods


# Academic Credentials 
**<span style="font-size:1em;">Jagannath University</span>** \hfill _Dhaka, Bangladesh_  
Master of Science in Microbiology\hfill _January 2019  - January 2020_

**<span style="font-size:1em;">Jagannath University</span>** \hfill _Dhaka, Bangladesh_  
Bachelor of Science in Microbiology\hfill _January 2016 - January 2019_


# Publications
1. Towhid, S. T., **Hossain, M. J.**, Sammo, M. A. S., & Akter, S. (2022). Perception of Students on Antibiotic Resistance and Prevention: An Online, Community-Based Case Study from Dhaka, Bangladesh. European Journal of Biology and Biotechnology, 3(3), 14–19. https://doi.org/10.24018/ejbio.2022.3.3.341

1. **Hossain, Md. J.**, Towhid, S. T., Sultana, S., Mukta, S. A., Gulshan, R., & Miah, S. (2022). Knowledge and attitudes towards thalassemia among university students in Bangladesh. medRxiv. https://doi.org/10.1101/2022.09.19.22280125 

2. **Hossain, Md. J.**, Towhid, S. T., Akter, S., Shahjahan, M., Roy, T., Akter, B., & Nodee, T. A. (2022). Self‑management of diabetic patients from the urban areas in Bangladesh. medRxiv. https://doi.org/10.1101/2022.08.23.22279128

# Working Papers 
1. **Hossain, Md. J.**, Md Wahidul Islam, Rukaiya Ummi Moon, Rubaiya Gulshan, Sumaiya Akter Mukta, Mousumi Karmakar, Sabia Sultana,Md. Sharif Miah, Md. Ariful Islam (2021). Quality of Life among Bangladeshi Patients with Thalassemia using the SF-36 Questionnaire.

2. **Hossain, Md. J.**, Abul Kalam Azad, Md. Wahidul Islam, Muhibullah Shahjahan (2022). Factors influencing knowledge of antibiotic usage among patients of school-going children. 

3. **Hossain, Md. J.**, Abul Kalam Azad, Md. Atik Shahriar Sammo (2022). A KAP Study on the Impact of C-section on Infant Gut Microbiota among Public University Students in Bangladesh

4. **Hossain, Md. J.**, Towhid, S. T.,Abul Kalam Azad, Manisha Das, Wahidul Islam, Muhibullah Shahjahan (2022). The role of community participation and social engagement in the prevention and control of dengue fever in Dhaka City

\pagebreak 
# Skills 
- **Programming Languages:** SQL, Python, R, Julia, JavaScript
- **Big Data Frameworks:** Dask, PySpark
- **Analytics Softwares:** SPSS, PowerBI, Microsoft Excel
- **Survey Tools:** RedCap, KoboToolBox, Google Forms
- **Miscellaneous Skills:** UNIX, Version Control(Git), Web Scraping, APIs, Visualizations


# Projects 
**<span style="font-size:1em;">Bioinformatics Approach for Profiling Antibiotic Resistance genes from Metagenomic DNA Sequence</span>** \hfill _\href{https://github.com/hossainlab/ARGs}{\faGithub}_ 
 
- **Aims:** To Profiling and predicting of antimicrobial-resistance antibiotic resistance genes from  metagenomic DNA sequences.
- **Technical Skills:** QIME2, DADA2, Bash 

**<span style="font-size:1em;">Heart Disease Analysis and Prediction Using Machine Learning</span>** \hfill _\href{https://github.com/hossainlab/Heart-Study}{\faGithub}_ 
 
- **Aims:** With the dataset provided for heart analysis, we have to analyse the possibilities of heart attack on the basis of various features, and then the prediction from the analysis will tell us that whether an individual is prone to heart attack or not.
- **Technical Skills:** Pandas, NumPy, Matplotlib, Seaborn, Scikit-learn 




# Teaching 
**<span style="font-size:1em;">Jagannath University, Dhaka</span>** \hfill _\href{https://jnu.ac.bd/dept/portal/web/microbiology}{Website}_   
Teaching Assistant, Department of Microbiology \hfill _October 2022 - Present_ 

Assisted Dr. Abul Kalam Azad, created course materials on undergrad level public health and hygiene. 

**<span style="font-size:1em;">Undergraduate Research Training Program (URTP)</span>** \hfill _\href{https://github.com/chiraleducation/URTP}{Course Website}_     
Lead Organizer & Instructor \hfill _January 2022 - Present_ 

The Undergraduate Research Training Program (URTP) aims to develop better-prepared undergraduate researchers. 

**<span style="font-size:1em;">Health Research ToolBox: A Step by Step Guide for Beginners (Cohort 2) </span>** \hfill _\href{https://github.com/chiraleducation/HRT}{Course Website}_  
Lead Organizer & Instructor \hfill _June 2021 - Present_ 

This course will give students a foundation in research principles and practice, mainly applied to public health.

**<span style="font-size:1em;">Genomic Data Science with R: Making Sense of Genomic Data </span>** \hfill _\href{https://github.com/chiraleducation/GDS}{Course Website}_  
Lead Organizer & Instructor \hfill _January 2022 - Present_

This course will give students a foundation in genomic research principles and practice, mainly applied to public health. 

**<span style="font-size:1em;">Python for Life Sciences - A Step by Step Guide for Life Scientists</span>** \hfill _\href{https://github.com/hossainlab/PY4LS}{\faGithub}_  
Lead Organizer & Instructor \hfill _June 2022 - July 2022_


# References

<span style="font-size:1em;">Syeda Tasneem Towhid, Ph.D.</span> \hfill towidst@mib.jnu.ac.bd  
Assistant Professor, Department of Microbiology, Jagannath University, Dhaka \hfill +8801746208281

<span style="font-size:1em;">Abul Kalam Azad, Ph.D.</span> \hfill akazad88@mib.jnu.ac.bd  
Associate Professor, Department of Microbiology, Jagannath University, Dhaka \hfill +8801732788272

<span style="font-size:1em;">Dr. Kamrun Nahar Koly</span> \hfill koly@icddrb.org  
Assistant Scientist, Health Systems and Population Studies Division, ICDDR,B \hfill +8801717190955



